[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect all routes to index.html (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
